# Generated by Django 2.0.5 on 2018-06-14 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_professor'),
        ('turmas', '0015_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.CharField(choices=[('1bimestre', '1º Bimestre'), ('2bimestre', '2º Bimestre'), ('3bimestre', '3º Bimestre'), ('4bimestre', '4º Bimestre')], max_length=12)),
                ('arquivo', models.FileField(upload_to='')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma')),
            ],
        ),
    ]
