# Generated by Django 2.0.5 on 2018-06-14 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coodenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('formacao', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
