# Generated by Django 2.0.5 on 2018-06-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coodenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coodenador',
            name='cpf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coodenador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coodenador',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coodenador',
            name='formacao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coodenador',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
