# Generated by Django 2.0.2 on 2018-04-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Turma')),
            ],
        ),
    ]
