# Generated by Django 2.0.2 on 2018-04-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_alunos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='alunos',
            new_name='users',
        ),
    ]
