# Generated by Django 2.0.3 on 2018-05-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0006_turma_estudantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='users',
        ),
    ]
