# Generated by Django 2.0.3 on 2018-05-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180513_1524'),
        ('turmas', '0009_auto_20180520_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.Aula')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Estudante')),
            ],
        ),
    ]
