# Generated by Django 2.0.3 on 2018-05-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0010_frequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='estudante',
        ),
    ]
