# Generated by Django 2.0.3 on 2018-05-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0011_remove_frequencia_estudante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aula',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
