# Generated by Django 2.0.2 on 2018-05-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0012_auto_20180520_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Estudante'),
        ),
    ]
