# Generated by Django 2.0.5 on 2018-06-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180614_1731'),
        ('turmas', '0015_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ManyToManyField(to='accounts.Professor'),
        ),
    ]
