# Generated by Django 2.0.5 on 2018-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180614_1731'),
        ('turmas', '0016_turma_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='coordenador',
            field=models.ManyToManyField(to='accounts.Coodenador'),
        ),
    ]
